import 'package:flutter/material.dart';
import 'package:global_compliance/Views/AboutDesktop/GlobalComplaincePortal/DashboardScreens.dart/InitialCheckScreen/InitialCheckScreen.dart';
import 'package:global_compliance/Views/AboutDesktop/GlobalComplaincePortal/DashboardScreens.dart/KpiReportScreen/KpiReportScreen.dart';
import 'package:global_compliance/view_Models/Models.dart';
import 'package:global_compliance/Views/AboutDesktop/GlobalComplaincePortal/DashboardScreens.dart/AccountingScreen/AccountingScreen.dart';
import 'package:global_compliance/Views/AboutDesktop/GlobalComplaincePortal/ManualScreeningDropdownScreens/DocumentForensicAnalysis/DocumentForensicAnalysisScreen.dart';
import 'package:global_compliance/Views/AboutDesktop/GlobalComplaincePortal/ManualScreeningDropdownScreens/EditIdentityVarificationScreen/EditIdentityVarificationScreen.dart';
import 'package:global_compliance/Views/AboutDesktop/GlobalComplaincePortal/ManualScreeningDropdownScreens/QuickDocumentScan/QuickDocumentScan.dart';
import 'package:global_compliance/Views/AboutDesktop/GlobalComplaincePortal/ManualScreeningDropdownScreens/QuickNameSearchScreen/QuickNameSearchScreen.dart';

final List<dynamic> ManualScreeningItems = [
  EmailIdentityVarification(),
  QuickNameSearchScreen(),
  QuickDocumentScan(),
  DocumentForensicAnalysisScreen()
];
final List<String> ManualScreeningItemsNames = [
  "Email Identity Varification",
  "Quick Name Search",
  "Quick Document Scan",
  "Document Forensic Analysis"
];
final List<String> items = [
  'Test Company',
  'Swiss AMF AG',
];
final List<String> StatusList = [
  'Status',
  'Accepted',
  'Rejected',
  'Requires Manual Completion',
  'Auto Completed',
  'Resubmitted',
  'Blacklisted',
  'Suspicious'
];
final List<String> TagsList = [
  'Select',
  'Suspecious',
  'Frozen',
  'Blacklisted',
  'Mobile'
];
final List<String> ForensicStatusList = [
  'Status',
  'Accepted',
  'Rejected',
];
final List<String> companiesList = [
  'Company',
  'Test Company',
  'Finclear Company',
  'Swiss AMF AG',
  'SIGTAX AG',
  'Global Compliance AG',
  'Swiss Global Trust AG',
  'Swiss Financial Hub AG',
  'Titan Holding AG',
  'Pillar Capital',
  'Aspen Asset Management',
];

final List<String> entendedSearchList = [
  "AML Search",
];
final List<String> dashboardItemsNames = ["Accounting", "KPI", "Initial Check"];
final List<Widget> dashboardItemsScreen = [
  AccountingScreen(),
  KpiReportScreen(),
  InitialCheckScreen()
];
List<ScreeningDataModel> screeningDataList = [
  ScreeningDataModel(
    name: "Osypov Dmytro",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    externalId: "P6946287",
    DocumentNumber: "605100B03",
    Nationality: "UKR",
    status: "Manual Screening",
    CompletedBy: "",
    Tag: "aa",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  ScreeningDataModel(
    name: "Osypov Dmytro",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    externalId: "P6946287",
    DocumentNumber: "605100B03",
    Nationality: "UKR",
    status: "Manual Screening",
    company: "Test Company",
    CompletedBy: "",
    Tag: "sss",
    created: "10/20/2022, 5:31:16 PM",
  ),
  ScreeningDataModel(
    name: "Osypov Dmytro",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    externalId: "P6946287",
    DocumentNumber: "605100B03",
    Nationality: "UKR",
    CompletedBy: "",
    status: "Manual Screening",
    company: "Test Company",
    Tag: "ddd",
    created: "10/20/2022, 5:31:16 PM",
  ),
  ScreeningDataModel(
    name: "Osypov Dmytro",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    externalId: "P6946287",
    DocumentNumber: "605100B03",
    Nationality: "UKR",
    Tag: "fff",
    status: "Manual Screening",
    company: "Test Company",
    CompletedBy: "",
    created: "10/20/2022, 5:31:16 PM",
  ),
  ScreeningDataModel(
    name: "Osypov Dmytro",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    externalId: "P6946287",
    DocumentNumber: "605100B03",
    Nationality: "UKR",
    CompletedBy: "",
    status: "Manual Screening",
    company: "Test Company",
    Tag: "",
    created: "10/20/2022, 5:31:16 PM",
  ),
  ScreeningDataModel(
    name: "Osypov Dmytro",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    externalId: "P6946287",
    DocumentNumber: "605100B03",
    Nationality: "UKR",
    status: "Manual Screening",
    CompletedBy: "",
    company: "Test Company",
    Tag: "asas",
    created: "10/20/2022, 5:31:16 PM",
  ),
  ScreeningDataModel(
    name: "Geoffrey Allan Parr-Sm",
    screeningToken: "4cae0f3b-9f6d-4680-8009-820cb7b575a6",
    externalId: "U2117432",
    DocumentNumber: "605100B03",
    Nationality: "CHN",
    Tag: "asdsa",
    status: "Processing",
    CompletedBy: "",
    company: "Test Company",
    created: "8/7/2022, 5:30:04 PM",
  ),
  ScreeningDataModel(
    name: "Andrea Elia",
    screeningToken: "8fa46ecf-3278-4422-badc-b74c881d3321",
    externalId: "U3301542",
    DocumentNumber: "",
    Nationality: "KOR",
    status: "Processing",
    company: "Test Company",
    Tag: "sadas",
    CompletedBy: "",
    created: "5/30/2022, 6:28:22 PM",
  ),
  ScreeningDataModel(
    name: "André Louis Genséric Co",
    screeningToken: "99b47c0d-d9e0-4a05-987d-db9258fb80ef",
    externalId: "U2117432",
    DocumentNumber: "605100B03",
    Nationality: "GBR",
    status: "Manual Screening",
    Tag: "sdsad",
    CompletedBy: "",
    company: "Test Company",
    created: "8/7/2022, 5:30:04 PM",
  ),
];

List<ForensicAnalysisDataModel> ForensicAnalysisDataList = [
  ForensicAnalysisDataModel(
    id: "Osypov Dmytro",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    tag: "Soft",
    status: "Manual Screening",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  ForensicAnalysisDataModel(
    id: "Geoffrey Allan Parr-Sm",
    screeningToken: "4cae0f3b-9f6d-4680-8009-820cb7b575a6",
    tag: "Software Engineer",
    status: "Processing",
    company: "Test Company",
    created: "8/7/2022, 5:30:04 PM",
  ),
  ForensicAnalysisDataModel(
    id: "Geoffrey Allan Parr-Sm",
    screeningToken: "4cae0f3b-9f6d-4680-8009-820cb7b575a6",
    tag: "Software Engineer",
    status: "Processing",
    company: "Test Company",
    created: "8/7/2022, 5:30:04 PM",
  ),
  ForensicAnalysisDataModel(
    id: "Geoffrey Allan Parr-Sm",
    screeningToken: "4cae0f3b-9f6d-4680-8009-820cb7b575a6",
    tag: "Software Engineer",
    status: "Processing",
    company: "Test Company",
    created: "8/7/2022, 5:30:04 PM",
  ),
  ForensicAnalysisDataModel(
    id: "Geoffrey Allan Parr-Sm",
    screeningToken: "4cae0f3b-9f6d-4680-8009-820cb7b575a6",
    tag: "Software Engineer",
    status: "Processing",
    company: "Test Company",
    created: "8/7/2022, 5:30:04 PM",
  ),
  ForensicAnalysisDataModel(
    id: "Geoffrey Allan Parr-Sm",
    screeningToken: "4cae0f3b-9f6d-4680-8009-820cb7b575a6",
    tag: "Software Engineer",
    status: "Processing",
    company: "Test Company",
    created: "8/7/2022, 5:30:04 PM",
  ),
  ForensicAnalysisDataModel(
    id: "Andrea Elia",
    screeningToken: "8fa46ecf-3278-4422-badc-b74c881d3321",
    tag: "TEST",
    status: "Processing",
    company: "Test Company",
    created: "5/30/2022, 6:28:22 PM",
  ),
  ForensicAnalysisDataModel(
    id: "André Louis Genséric Co",
    screeningToken: "99b47c0d-d9e0-4a05-987d-db9258fb80ef",
    tag: "Robin passport",
    status: "Manual Screening",
    company: "Test Company",
    created: "8/7/2022, 5:30:04 PM",
  ),
];
List<InvitationSentModel> InvitationSentList = [
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
  InvitationSentModel(
    name: "Ayaz",
    screeningToken: "3fde1490-0a4e-4fb3-9a3f-081ce1d6bb74",
    Email: "ayazqadri111@gmail.com",
    Completed: "assets/image/tick.png",
    UpdateRequested: "assets/image/tick.png",
    LinkOpened: "9/20/2022, 4:23:05 PM",
    company: "Test Company",
    created: "10/20/2022, 5:31:16 PM",
  ),
];
List<WebHookManagmentModel> WebHookManagmentList = [
  WebHookManagmentModel(
    WebHookUrl: "be68b66b-72ba-43a0-9c43a0-9c59-687b2f61dba9",
    WebHookSecret: "********",
    btnText: "Remove",
  ),
  WebHookManagmentModel(
    WebHookUrl: "be68b43a0-9c2ba-43 dba9",
    WebHookSecret: "********",
    btnText: "Remove",
  ),
  WebHookManagmentModel(
    WebHookUrl: "72ba-43a0-9c59-687b2f61dba9be68b66b-",
    WebHookSecret: "********",
    btnText: "Remove",
  ),
];

List<CredentiaManagmentModel> CredentiaManagmentList = [
  CredentiaManagmentModel(
    clientId: "be68b66b-72ba-43a0-9c59-687b2f61dba9",
    secret: "********",
    btnText: "Remove",
  ),
  CredentiaManagmentModel(
    clientId: "be68b66b-72ba-43a0-9c59-687b2f61dba9",
    secret: "********",
    btnText: "Remove",
  ),
  CredentiaManagmentModel(
    clientId: "be68b66b-72ba-43a0-9c59-687b2f61dba9",
    secret: "********",
    btnText: "Remove",
  ),
  CredentiaManagmentModel(
    clientId: "be68b66b-72ba-43a0-9c59-687b2f61dba9",
    secret: "********",
    btnText: "Remove",
  ),
];

List<String> country_list = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antigua",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia ",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D Ivoire",
  "Croatia",
  "Cruise Ship",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Polynesia",
  "French West Indies",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kuwait",
  "Kyrgyz Republic",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Pierre ",
  "Samoa",
  "San Marino",
  "Satellite",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "St Kitts",
  "St Lucia",
  "St Vincent",
  "St. Lucia",
  "Sudan",
  "Suriname",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor L'Este",
  "Togo",
  "Tonga",
  "Trinidad ",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks ",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (US)",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
List<String> ListAMLOFACPEPMatches = [
  "Exact(>=95%)",
  "Strong(<=95% and >=85%)",
  "Medium(<=85% and >=75%)",
  "Week(<75%)",
];
